version: '3'
services:
  app:
    restart: always
    image: registry.lucasrobin.fr/i2fc-apc-report-app
    container_name: i2fc-apc-report-app
    depends_on:
      - db
    networks:
      - apc_report
    volumes:
      - ./app/:/www
      - /www/vendor/
      - ./app/dockerfs/var/log/nginx:/var/log/nginx
    ports:
      - 8888:80

  db:
    restart: always
    image: mariadb:10.5.8
    container_name: i2fc-apc-report-mysql
    environment:
      MYSQL_DATABASE: apc_report
      MYSQL_ROOT_PASSWORD: www@i2fc@2020
      MYSQL_PASSWORD: 20059478Lr
      MYSQL_USER: www
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - apc_report
  
  adminer:
    restart: always
    image: adminer
    container_name: i2fc-apc-report-adminer
    ports:
      - 8181:8080
    networks:
      - apc_report

networks:
    apc_report:
