version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    image: registry.lucasrobin.fr/i2fc-apc-report-app
    container_name: i2fc-apc-report-app
    working_dir: /www
    depends_on:
      - db
    networks:
      - apc-report-network
    volumes:
      - ./dockerfs/var/log/nginx:/var/log/nginx

  db:
    restart: unless-stopped
    image: mysql:5.7
    container_name: i2fc-apc-report-mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - apc-report-network

networks:
    apc-report-network:
