export default {
  LOGIN: '/api/login',
  FETCH_REPORTS: '/api/reports',
  UPDATE_REPORT: '/api/report/',
  FETCH_REPORT: '/api/report/',
  FETCH_USERS: '/api/users',
  FETCH_USER: '/api/user/',
  FETCH_APPOINTMENTS: '/api/appointments',
  FETCH_APPOINTMENT: '/api/appointment/',
  FETCH_CUSTOMERS: '/api/customers',
  FETCH_CUSTOMER: '/api/customer/',
  DELETE_CUSTOMER: '/api/customer/',
  UPDATE_CUSTOMER: '/api/customer/',
  FETCH_SETTINGS: '/api/settings',
  STORE_APPOINTMENT: '/api/appointment',
  DELETE_APPOINTMENT: '/api/appointment/',
  UPDATE_APPOINTMENT: '/api/appointment/',
  NEWSLETTER_CUSTOMER: '/api/newsletter/customers',
};
